enable-magisk-update = true # set this to false if you do not want to receive updates for the module in magisk app
parallel-jobs = 1

# add 'enabled = false' for not patching a specific app or remove it from the config
# see https://github.com/j-hc/revanced-magisk-module/blob/main/CONFIG.md for more detailed explanations

# you can use rvmm-config-gen to generate a config

[Music]
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube-music/"
patches-source = "inotia00/revanced-patches"
cli-source = "inotia00/revanced-cli"
integrations-source = "inotia00/revanced-integrations"
rv-brand = "inotia00 ReVanced"
arch = "arm64-v8a"
build-mode = "module"
included-patches = "'Bitrate default value' 'Certificate spoof' 'Dark theme' 'Disable Cairo splash animation' 'Disable DRC audio' 'Disable music video in album' 'Enable landscape mode' 'Fix playback' 'Flyout menu components' 'Hide action bar components' 'Hide ads' 'Navigation bar components' 'Remove background playback restrictions' 'Remove viewer discretion dialog' 'Return YouTube Dislike' 'Sanitize sharing links' 'Settings for YouTube Music' 'SponsorBlock' 'Video playback'"
exclusive-patches = true
